### ISSUE TITLE
Bug Report: Emoji causing a screen display to be off

### ISSUE THREAD

**Issue by GamerCreator1** [TeamDmod/dmod#39]
https://beta.dmod.gg/servers/331039920107814943
![image](https://user-images.githubusercontent.com/58714825/129100860-06257d31-0524-48b7-8a24-1fcff5ab2c3c.png)

**Comment by MattA-Official** [comment]
This will be fixed with the restyle, but I have two options: Show all the emojis and wrap them, or just show the first _x_ emojis?

**Comment by vagabondlol** [comment]
> This will be fixed with the restyle, but I have two options: Show all the emojis and wrap them, or just show the first _x_ emojis?

I'm thinking show the first x amount of emojis to avoid bloat as some communities have hundreds

**Comment by GamerCreator1** [comment]
> > This will be fixed with the restyle, but I have two options: Show all the emojis and wrap them, or just show the first _x_ emojis?
> 
> I'm thinking show the first x amount of emojis to avoid bloat as some communities have hundreds

If we are doing this way, the linked pull request will fix it.

**Comment by Wilbert-mad** [comment]
> This will be fixed with the restyle, but I have two options: Show all the emojis and wrap them, or just show the first _x_ emojis?

We can have a max of 50 emojis and wrap those with an optional expansion. Display 10 and expand to 50.
