### ISSUE TITLE
Dispatch Page Issue

### ISSUE THREAD

**Issue by TypedStream** [TeamDmod/dmod#77]
![9D689C68-767E-49F0-AB1E-FA67D6E3C94E](https://user-images.githubusercontent.com/89241597/141934891-b6489cf3-88ef-433c-b7cd-9903008a42cd.jpeg)

I Have Found a bug in the dispatch page on the dmod site, with the text not showing for the server with dispatches.

**Comment by TypedStream** [comment]
Sorry, didnt write this above, it was on google chrome on an ipad

**Comment by Codeize** [comment]
Hi there!
We're aware of the responsiveness issues with the dispatch site, and we are working to redesign it and make it a lot nicer than it was prior.
Just a small thing, this is for the main Dmod site, this issue belongs [in the prelaunch site repository](https://github.com/TeamDmod/prelaunch)
Thanks! 😄
